In [2]:
import torch

In [3]:
# Creating tensors
x = torch.tensor([1, 2])
y = torch.tensor([[1, 2], [3, 4]])
z = torch.rand(3, 2)
print(z, z.shape, z.dtype, z.device)

tensor([[0.3788, 0.9273],
        [0.0085, 0.5893],
        [0.6941, 0.5422]]) torch.Size([3, 2]) torch.float32 cpu


In [4]:
# Broadcasting
res1 = x + y
print(res1)
res2 = x + z
print(res2)

tensor([[2, 4],
        [4, 6]])
tensor([[1.3788, 2.9273],
        [1.0085, 2.5893],
        [1.6941, 2.5422]])


In [5]:
# Reshaping
z = z.view(2, 3)
print(z)

tensor([[0.3788, 0.9273, 0.0085],
        [0.5893, 0.6941, 0.5422]])


In [6]:
# Converting to numpy
z_np = z.numpy()
print(z_np)

[[0.37881458 0.92725205 0.00847691]
 [0.5892806  0.6941213  0.54220754]]


In [7]:
# Slice operations
print(z)
print(z[0, 1])
print(z[0, :])
print(z[:, 1])
print(z[0, 1].item(), type(z[0, 1].item()))


tensor([[0.3788, 0.9273, 0.0085],
        [0.5893, 0.6941, 0.5422]])
tensor(0.9273)
tensor([0.3788, 0.9273, 0.0085])
tensor([0.9273, 0.6941])
0.9272520542144775 <class 'float'>


In [8]:
# Concatenation
x = torch.tensor([[1, 2], [3, 4]])
y = torch.tensor([[5, 6], [7, 8]])
z = torch.cat([x, y], dim=0)
print(z)

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])


In [9]:
# Element-wise operations
x = torch.tensor([[1, 2], [3, 4]])
y = torch.tensor([[5, 6], [7, 8]])
z = x + y
z

tensor([[ 6,  8],
        [10, 12]])

In [10]:
# Matrix multiplication
x = torch.tensor([[1, 2], [3, 4]])
y = torch.tensor([[5, 6], [7, 8]])
z = x @ y
print(z)

tensor([[19, 22],
        [43, 50]])


In [25]:
# Simple optimization example with torch tensor
x = torch.tensor([1.0, 2.0, 3.0], requires_grad=True)
target = 0.
for i in range(100):
    y = x + 2
    z = y * y * 2
    out = z.mean()
    loss = (out - target) ** 2
    if i % 10 == 0:
        print(loss)
        print(x)
    # Backward pass
    x.grad = None
    loss.backward()
    
    # Update weights
    x.data += -0.01 * x.grad


tensor(1111.1111, grad_fn=<PowBackward0>)
tensor([1., 2., 3.], requires_grad=True)
tensor(0.1175, grad_fn=<PowBackward0>)
tensor([-1.6958, -1.5944, -1.4930], requires_grad=True)
tensor(0.0836, grad_fn=<PowBackward0>)
tensor([-1.7206, -1.6274, -1.5343], requires_grad=True)
tensor(0.0626, grad_fn=<PowBackward0>)
tensor([-1.7401, -1.6534, -1.5668], requires_grad=True)
tensor(0.0486, grad_fn=<PowBackward0>)
tensor([-1.7560, -1.6747, -1.5933], requires_grad=True)
tensor(0.0389, grad_fn=<PowBackward0>)
tensor([-1.7693, -1.6924, -1.6155], requires_grad=True)
tensor(0.0318, grad_fn=<PowBackward0>)
tensor([-1.7806, -1.7075, -1.6344], requires_grad=True)
tensor(0.0265, grad_fn=<PowBackward0>)
tensor([-1.7904, -1.7206, -1.6507], requires_grad=True)
tensor(0.0224, grad_fn=<PowBackward0>)
tensor([-1.7990, -1.7320, -1.6650], requires_grad=True)
tensor(0.0192, grad_fn=<PowBackward0>)
tensor([-1.8066, -1.7422, -1.6777], requires_grad=True)
